import java.awt.*;
import javax.swing.*;

public class RoomExtrasTable extends JPanel {
    private GridLayout gridLayout;

    public RoomExtrasTable() {
	gridLayout = new GridLayout( 16, 6 );
	this.setLayout( gridLayout );	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "Monday" ));	
	this.add( new JLabel( "Tuesday" ));	
	this.add( new JLabel( "Wednesday" ));	
	this.add( new JLabel( "Thursday" ));	
	this.add( new JLabel( "Friday" ));	
	this.add( new JLabel( "8 AM-9 AM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "9 AM-10 AM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "10 AM-11 AM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "11 AM-12 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "12 PM-1 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "1 PM-2 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "2 PM-3 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "3 PM-4 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "4 PM-5 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "5 PM-6 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "6 PM-7 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "7 PM-8 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "8 PM-9 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "9 PM-10 PM" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	this.add( new JLabel( "" ));	
	
	//this.etGridColor(Color.blue);
	//this.setShowGrid(true);
	
    }
}
